//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspenlaub.Net.GitHub.CSharp.PressEnter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspenlaub.Net.GitHub.CSharp.PressEnter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endless refresh is requested.
        /// </summary>
        internal static string EndlessRefresh {
            get {
                return ResourceManager.GetString("EndlessRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name has been entered.
        /// </summary>
        internal static string FileNameEntered {
            get {
                return ResourceManager.GetString("FileNameEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name is empty.
        /// </summary>
        internal static string FileNameIsEmpty {
            get {
                return ResourceManager.GetString("FileNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with that name does not exist.
        /// </summary>
        internal static string FileWithThatNameDoesNotExist {
            get {
                return ResourceManager.GetString("FileWithThatNameDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First command line argument is &quot;{0}&quot;.
        /// </summary>
        internal static string FirstCommandLineArgument {
            get {
                return ResourceManager.GetString("FirstCommandLineArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of refresh actions is limited to {0}.
        /// </summary>
        internal static string LimitedNumberOfRefreshs {
            get {
                return ResourceManager.GetString("LimitedNumberOfRefreshs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pane was found with a non-empty name that does not contain &apos;Desktop&apos;.
        /// </summary>
        internal static string NoPaneWasFound {
            get {
                return ResourceManager.GetString("NoPaneWasFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upload window found.
        /// </summary>
        internal static string NoUploadWindowFound {
            get {
                return ResourceManager.GetString("NoUploadWindowFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of command line arguments is {0}.
        /// </summary>
        internal static string NumberOfArguments {
            get {
                return ResourceManager.GetString("NumberOfArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of refresh actions is now {0}.
        /// </summary>
        internal static string NumberOfRefrehsIsNow {
            get {
                return ResourceManager.GetString("NumberOfRefrehsIsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing....
        /// </summary>
        internal static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
    }
}
